### PR TITLE
fix: add websocket support

### PR DESCRIPTION
**Pull request by mfmarche**
Adds websocket support to stomp.py.

- Support for ws and wss schemes
- tested under rabbitmq

### CODE REVIEW

**Comment by mfmarche** [comment]
#342 adds websocket support

**Comment by jasonrbriggs** [comment]
Merged belatedly.  Thanks for the contribution.

**Comment by mfmarche** [comment]
thanks @jasonrbriggs . What is this repositories process for dev to get published to pypi.org?

**Comment by jasonrbriggs** [comment]
I plan to release it soon.  But thinking that I would like to move the websocket support into stomp.adapter to keep things clean.  Have that prepped locally but have a few other things to complete as well.

**Pull request merged**
