### PR TITLE
Do not try to decode nonexistent message bodies

### PR DESCRIPTION
**Pull request by scop**
The test case is untested as I don't have the setup required for running the suite right now.

### CODE REVIEW

**Comment by scop** [comment]
What I saw the issue with was actually heartbeat messages.

**Comment by jasonrbriggs** [comment]
Test doesn't work because there's an assert that the body must be provided:

```python
assert body is not None, "'body' is required"
```

Do you have the actual error/stacktrace you were trying to fix?

**Comment by scop** [comment]
Yes, this is the stacktrace I see on inbound heartbeat (from ActiveMQ Artemis):

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "[...]/virtualenv/lib/python3.4/site-packages/stomp/transport.py", line 295, in __receiver_loop
    f.body = decode(f.body)
  File "[...]/virtualenv/lib/python3.4/site-packages/stomp/backward3.py", line 15, in decode
    return byte_data.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by jasonrbriggs** [comment]
Implemented separately, and added a unit test to cover the change.

**Pull request closed without merging**
